### ISSUE TITLE
点击标签，左侧路由没有变换

### ISSUE THREAD

**Issue by qld-cf** [Fengly0503/ant_pro_tabs#1]

**Comment by Fengly0503** [comment]
是的，周末有空捣鼓下更新一个版本

**Comment by qld-cf** [comment]
@Fengly0503 你那边应该可以搞，我现在的项目，所有属性都匹配了，同样代码，竟然无法联动，真的服了

**Comment by Fengly0503** [comment]
> @Fengly0503 你那边应该可以搞，我现在的项目，所有属性都匹配了，同样代码，竟然无法联动，真的服了

已经修复
