### ISSUE TITLE
您好，我想问下，关于tabs切换，表单数据不刷新您是如何做的，用到了umi吗

### ISSUE THREAD

**Issue by 1101916341** [Fengly0503/ant_pro_tabs#3]
您好，我想问下，关于tabs切换，表单数据不刷新您是如何做的，用到了umi吗？如果用到了，那其中的作用是什么啊，方便帮忙解答一下吗？非常感谢

**Comment by Fengly0503** [comment]
tabs切换表单不刷新的根本原因是tabs内的子组件在切换时不销毁就可以了（默认就是这样），对于单页面应用来说不管什么展现形式，都是根组件的子组件而已，umi只是对dva以及常用模板的整合封装，用不用都可以
