### ISSUE TITLE
如果在当前标签页中使用modal时，切换到其它标签时，这个modal还是会多次执行，有什么办法？

### ISSUE THREAD

**Issue by ghfhaifeng110** [Fengly0503/ant_pro_tabs#6]
如果在当前标签页中使用modal时，切换到其它标签时，这个modal还是会多次执行，有什么办法？

**Comment by Fengly0503** [comment]
正常情况下，modal框弹出以后背景是会遮盖tab栏的，可以利用modal框的getContainer属性将其指定到所属tab页的内容组件内，类似：
`<Modal getContainer={document.getElementById('parent-id')}
      ......
</Modal>`
在其所属的组件内：

`<div id="parent-id">......<div>`

如果遮盖的范围有出入，可以通过全局样式覆盖modal原来的样式来调整
